version: '3'

services:

  mysql:
    image: mysql:8.0

    env_file:
      - secret.env
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_storage:/data


  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data/
    env_file:
      - secret.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


  springboot:
    build: ./
    restart: unless-stopped
    depends_on:
      - redis
      - mysql
      - minio
    env_file:
      - secret.env
    image: cloud
    ports:
      - '8080:8080'


volumes:
  mysql_data:
  minio_storage:
  redis_storage: