server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  datasource:
    name: MySQL
    generate-unique-name: false
    hikari:
      username: root
      password: password
    url: jdbc:mysql://localhost:3306/USER_INFO?useSSL=false
  session:
    redis:
      save-mode: always
  data:
    redis:
      host: localhost
      password:
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql


