server:
  port: 8080

minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}
  bucketName: ${BUCKET_NAME}
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: false
  datasource:
    name: MySQL
    generate-unique-name: false
    hikari:
      username: root
      password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:mysql://mysql:3306/USER_INFO?useSSL=false&allowPublicKeyRetrieval=true
  session:
    redis:
      save-mode: always
  data:
    redis:
      port: 6379
      host: redis

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql




